### PR TITLE
make autobuild: use docker

### PR DESCRIPTION
**Pull request by alxndrsn**
Replaces requirement for a local, functioning python env with requirement for a local, functioning docker env.

### CODE REVIEW

**Comment by lognaturel** [comment]
> Replaces requirement for a local, functioning python env with requirement for a local, functioning docker env.

Hah! Can we please make this additive rather than a replacement? Maybe `make docker-autobuild` or just `make docker`?

**Comment by alxndrsn** [comment]
Is `autobuild` idiomatic?  What about having `make dev-local` and `make dev-docker`?

**Comment by lognaturel** [comment]
It's from https://pypi.org/project/sphinx-autobuild/ Given it's been like this for years, it's in a lot of our fingers. We could add a `dev-local` "alias" if you want but let's keep `autobuild` as well.

**Comment by alxndrsn** [comment]
:+1:

How about `make autobuild-docker`?  That should keep muscle memory for `make autobuild` working ok, but also make the docker option discoverable without needing extra documentation.

**Comment by lognaturel** [comment]
Love it, thanks!

**Pull request merged**
